#!/usr/bin/env bash

proj=everyclient.csproj

cd `dirname $0`
{
    sed -n -e '1,/<ItemGroup Label="assets">/ p' $proj
    find -L assets -type f | \
        sort -f | sed -e 's;/;\\;g' -e 's/^/    <Content Include="/' -e 's;$;" />;'
    sed -n -e '/<ItemGroup Label="assets">/,$ p' $proj | sed -n -e '/<\/ItemGroup>/,$ p';
} > /tmp/$proj
mv /tmp/$proj $proj
